# Generated by Django 4.1.3 on 2022-11-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='comments',
        ),
    ]
