# Generated by Django 4.1.3 on 2022-11-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_orders_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.comments', verbose_name='Комментарии'),
        ),
    ]
