# Generated by Django 4.1.3 on 2022-11-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orders_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='shop.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.comments', verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='shop.tags', verbose_name='Теги'),
        ),
    ]
