# Generated by Django 4.1.3 on 2022-11-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_orders_category_alter_orders_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'default_related_name': 'categories', 'ordering': ['slug'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'default_related_name': 'tags', 'ordering': ['slug'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
