# Generated by Django 4.1.3 on 2022-11-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_categories_options_remove_comments_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='category',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.orders', verbose_name='Обьявление'),
        ),
    ]
