# Generated by Django 4.1.3 on 2022-11-22 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orders_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(max_length=500, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='shop.orders', verbose_name='Обьявление'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='shop.categories', verbose_name='Категория'),
        ),
    ]
